#!/usr/bin/env sh
if [ -f installed_files.txt ]; then
    cat installed_files.txt | xargs rm -rf && \
	echo "uninstalled/removed: "$(cat installed_files.txt)
else
    echo "\"installed_files.txt\" does not exists"
    echo "cannot uninstall!"
fi
