#!/bin/bash
# fuse_git_bare_fs tree server mountpoint
mkdir server
mkdir server/repo2
mkdir client
mkdir mountpoint

(
    cd server || exit 1
    git init --bare repo1.git
    git init --bare repo2/repo2.git
    git init --bare repo3.git
) || exit 1

cd client || exit 1
git clone ../server/repo1
git clone ../server/repo2/repo2
git clone ../server/repo3

cd repo1 || exit 1
echo f1 > f1; git add f1; git commit -m f1
git push # init master repository on remote
git annex init # init git-annex locally
echo f2 > f2; git annex add f2; git commit -m f2
git annex sync # init git-annex on remote
git annex sync --content # sync content to remote
echo f3 > f3; git annex add f3; git commit -m f3;
git annex sync
cd ..

cd repo2 || exit 1
git annex init # init git-annex locally
mkdir f1
echo f1 > f1/f1
git annex add f1/f1; git commit -m f1
git push # init master repository on remote
echo f2 > f2; chmod +x f2; git annex add f2; git commit -m f2
git annex sync # init git-annex on remote
git annex sync # init git-annex on remote
git annex sync --content # sync content to remote
ln -s f2 f3
git annex add f3; git commit -m f3;
git annex sync
cd ..

cd repo3 || exit 1
git annex init
echo f1 > f1; git add f1; git commit -m f1; git push
cd ..
