#!/bin/bash

function test_access() {
    r="$1"
    u="$2"
    if [ "$r" = "repo1" ]; then
	if [ "$u" = "user1" ]; then
	    return 0
	elif [ "$u" = "user2" ]; then
	    return 1
	fi
    elif [ "$r" = "repo2" ]; then
	if [ "$user" = "user1" ]; then
	    return 0
	elif [ "$u" = "user2" ]; then
	    return 1
	fi
    else
	return 0
    fi
}

if [ "$1" = "list-users" ]; then
    echo user1
    echo user2
elif [ "$1" = "list-phy-repos" ]; then
    echo "repo1"
    echo "repo2"
    echo "repo3"
elif [ "$1" = "access" ]; then
    if [ "$2" = "%" ]; then
	repo="$2"
	user="$3"
	for repo in $(< /dev/stdin); do
	    test_access "$repo" "$user"
	    if [ $? = 1 ]; then
		echo $repo $user DENIED by definition
	    else
		echo $repo $user OK
	    fi
	done
    else
	repo="$3"
	user="$4"
	test_access "$repo" "$user"
	exit $?
    fi
elif [ "$1" = "createenv" ]; then
    # fuse_git_bare_fs tree -get_user_list_from_gitolite -provide_htaccess -gitolite_cmd /full_path/gitolite server mountpoint
    mkdir server
    (
	cd server || exit 1
	git init --bare gitolite-admin.git
	git init --bare repo1.git
	git init --bare repo2.git
	git init --bare repo3.git
    ) || exit 1
    mkdir client
    (
	cd client || exit 1
	git clone ../server/gitolite-admin
	git clone ../server/repo1
	git clone ../server/repo2
	git clone ../server/repo3
	cd gitolite-admin || exit 1
	echo a > a; git add a; git commit -m a; git push
    ) || exit 1
    (
	cd client/repo1 || exit 1
	echo b > b; git add b; git commit -m b; git push
    ) || exit 1
    (
	cd client/repo2 || exit 1
	echo c > c; git add c; git commit -m c; git push
    ) || exit 1
    (
	cd client/repo3 || exit 1
	echo d > d; git add d; git commit -m d; git push
    ) || exit 1
    mkdir mountpoint
    echo "user1" > users
    echo "user2" >> users
fi
