# https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

# todo:
# https://docs.github.com/en/actions/guides/building-and-testing-python
# https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows

name: unittest_pytest_coverage_doc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pep8_check:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: apt-get update
      run: sudo apt-get update
    - name: install dependencies for PEP 8 code style check (ubuntu packages)
      run: sudo apt-get install pep8 pylint python3-recommonmark python3-pytest python3-dulwich
    - name: pep8 version
      run: pep8 --version
    - name: pylint version
      run: pylint --version
    - name: check PEP 8 code style
      run: pep8 --show-source --show-pep8 --statistics $(find -name "*.py")
    - name: run pylint with finding similarities (may fail)
      run: pylint -j 3 --include-naming-hint=y --good-names=i,j,k,fd $(find -name "*.py")
      continue-on-error: true
    - name: run pylint
      run: pylint -j 3 --include-naming-hint=y --good-names=i,j,k,fd --disable=similarities $(find -name "*.py")

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      # https://github.com/marketplace/actions/checkout
    - uses: actions/setup-python@v2
      # https://github.com/marketplace/actions/setup-python
    - uses: pre-commit/action@v2.0.3
      # https://github.com/pre-commit/action
      #continue-on-error: true

  ubuntu-2004_test_doc:
    needs: [pep8_check, pre-commit]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: apt-get update
      run: sudo apt-get update
    - name: install dependencies (ubuntu packages)
      run: sudo apt-get install python3-fusepy python3-pytest python3-pytest-cov python3-pytest-xdist python3-setuptools python3-dulwich git-annex python3-sphinx python3-sphinx-argparse python3-recommonmark latexmk texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
    - name: setup author identity for git commits
      run: |
        test -n "$(git config user.name)" || git config --global user.name $USER
        hostname=$HOSTNAME
        test -n "$hostname" || hostname="runner"
        test -n "$(git config user.email)" || git config --global user.email $(git config user.name)@$hostname
    - name: local unittest
      run: env python3 setup.py run_unittest --src local
    - name: local pytest
      run: env python3 setup.py run_pytest --src local
    - name: check_modules
      run: env python3 setup.py check_modules
    - name: check_modules_modulefinder
      run: env python3 setup.py check_modules_modulefinder
    - name: install fuse_git_bare_fs
      run: pip3 install .
    - name: unittest
      run: env python3 setup.py run_unittest
    - name: pytest
      run: env python3 setup.py run_pytest --parallel --coverage
    - name: build doc
      run: ./create_doc
    - name: uninstall dulwich (ubuntu packages)
      run: sudo apt-get remove python3-dulwich
    - name: local unittest (using git instead of dulwich)
      run: env python3 setup.py run_unittest --src local
    - name: local pytest (using git instead of dulwich)
      run: env python3 setup.py run_pytest --src local
    - name: unittest (using git instead of dulwich)
      run: env python3 setup.py run_unittest
    - name: pytest (using git instead of dulwich)
      run: env python3 setup.py run_pytest --parallel --coverage

  ubuntu-2204_test_doc:
    needs: [pep8_check, pre-commit]
#    runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: apt-get update
      run: sudo apt-get update
    - name: install dependencies (ubuntu packages)
      run: sudo apt-get install python3-fusepy python3-pytest python3-pytest-cov python3-pytest-xdist python3-setuptools python3-dulwich git-annex python3-sphinx python3-sphinx-argparse python3-recommonmark latexmk texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra fuse
    - name: setup author identity for git commits
      run: |
        test -n "$(git config user.name)" || git config --global user.name $USER
        hostname=$HOSTNAME
        test -n "$hostname" || hostname="runner"
        test -n "$(git config user.email)" || git config --global user.email $(git config user.name)@$hostname
    - name: local unittest
      run: env python3 setup.py run_unittest --src local
    - name: local pytest
      run: env python3 setup.py run_pytest --src local
    - name: check_modules
      run: env python3 setup.py check_modules
    - name: check_modules_modulefinder
      run: env python3 setup.py check_modules_modulefinder
    - name: install fuse_git_bare_fs
      run: pip3 install .
    - name: unittest
      run: env python3 setup.py run_unittest
    - name: pytest
      run: env python3 setup.py run_pytest --parallel --coverage
    - name: build doc
      run: ./create_doc
    - name: uninstall dulwich (ubuntu packages)
      run: sudo apt-get remove python3-dulwich
    - name: local unittest (using git instead of dulwich)
      run: env python3 setup.py run_unittest --src local
    - name: local pytest (using git instead of dulwich)
      run: env python3 setup.py run_pytest --src local
    - name: unittest (using git instead of dulwich)
      run: env python3 setup.py run_unittest
    - name: pytest (using git instead of dulwich)
      run: env python3 setup.py run_pytest --parallel --coverage

  opensuse_leap_154_test:
    runs-on: ubuntu-latest
    needs: [pep8_check, pre-commit]
    name: opensuse leap 15.4
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run test_suite in opensuse/leap:15.4
        run: sudo docker run --mount type=bind,source=$(pwd),destination=/app --rm --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined opensuse/leap:15.4 app/.github/workflows/do_test_opensuse_leap:15.4

  opensuse_leap_155_test:
    runs-on: ubuntu-latest
    needs: [pep8_check, pre-commit]
    name: opensuse leap 15.5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run test_suite in opensuse/leap:15.5
        run: sudo docker run --mount type=bind,source=$(pwd),destination=/app --rm --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined opensuse/leap:15.4 app/.github/workflows/do_test_opensuse_leap:15.5

  deploy_pages:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    runs-on: ubuntu-latest
    needs: [ubuntu-2004_test_doc, ubuntu-2204_test_doc, opensuse_leap_154_test, opensuse_leap_155_test]
    steps:
    - uses: actions/checkout@v3
    - name: apt-get update
      run: sudo apt-get update
    - name: install dependencies (ubuntu packages)
      run: sudo apt-get install python3-fusepy python3-pytest python3-pytest-cov python3-pytest-xdist python3-setuptools python3-dulwich git-annex python3-sphinx python3-sphinx-argparse python3-recommonmark latexmk texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra fuse
    - name: setup author identity for git commits
      run: |
        test -n "$(git config user.name)" || git config --global user.name $USER
        hostname=$HOSTNAME
        test -n "$hostname" || hostname="runner"
        test -n "$(git config user.email)" || git config --global user.email $(git config user.name)@$hostname
    - name: install fuse_git_bare_fs
      run: pip3 install .
    - name: create coverage report
      run: env python3 setup.py run_pytest --parallel --coverage
    - name: build doc
      run: ./create_doc
    - name: deploy pages
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: documentation
        folder: manual_fuse_git_bare_fs_html
